package eu.ebbitsproject.peoplemanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-15T23:24:51.382+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "RuleEngine", 
                  wsdlLocation = "http://localhost:8081/ruleengine?wsdl",
                  targetNamespace = "http://peoplemanager.ebbitsproject.eu/") 
public class RuleEngine extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://peoplemanager.ebbitsproject.eu/", "RuleEngine");
    public final static QName RuleEnginePort = new QName("http://peoplemanager.ebbitsproject.eu/", "RuleEnginePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/ruleengine?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RuleEngine.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/ruleengine?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RuleEngine(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RuleEngine(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleEngine() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RuleEngine(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RuleEngine(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RuleEngine(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns RuleEnginePortType
     */
    @WebEndpoint(name = "RuleEnginePort")
    public RuleEnginePortType getRuleEnginePort() {
        return super.getPort(RuleEnginePort, RuleEnginePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleEnginePortType
     */
    @WebEndpoint(name = "RuleEnginePort")
    public RuleEnginePortType getRuleEnginePort(WebServiceFeature... features) {
        return super.getPort(RuleEnginePort, RuleEnginePortType.class, features);
    }

}
