
package eu.ebbitsproject.peoplemanager;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-15T23:24:51.313+02:00
 * Generated source version: 3.0.1
 * 
 */
public final class RuleEnginePortType_RuleEnginePort_Client {

    private static final QName SERVICE_NAME = new QName("http://peoplemanager.ebbitsproject.eu/", "RuleEngine");

    private RuleEnginePortType_RuleEnginePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RuleEngine.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RuleEngine ss = new RuleEngine(wsdlURL, SERVICE_NAME);
        RuleEnginePortType port = ss.getRuleEnginePort();  
        
        {
        System.out.println("Invoking getEvents...");
        java.util.List<eu.ebbitsproject.peoplemanager.Event> _getEvents__return = port.getEvents();
        System.out.println("getEvents.result=" + _getEvents__return);


        }
        {
        System.out.println("Invoking insertEvent...");
        java.lang.String _insertEvent_arg0 = "";
        port.insertEvent(_insertEvent_arg0);


        }
        {
        System.out.println("Invoking isPersonAvailableById...");
        java.lang.String _isPersonAvailableById_arg0 = "";
        boolean _isPersonAvailableById__return = port.isPersonAvailableById(_isPersonAvailableById_arg0);
        System.out.println("isPersonAvailableById.result=" + _isPersonAvailableById__return);


        }
        {
        System.out.println("Invoking isPersonAvailableByRfid...");
        java.lang.String _isPersonAvailableByRfid_arg0 = "";
        boolean _isPersonAvailableByRfid__return = port.isPersonAvailableByRfid(_isPersonAvailableByRfid_arg0);
        System.out.println("isPersonAvailableByRfid.result=" + _isPersonAvailableByRfid__return);


        }
        {
        System.out.println("Invoking updateEvent...");
        java.lang.String _updateEvent_arg0 = "";
        port.updateEvent(_updateEvent_arg0);


        }
        {
        System.out.println("Invoking getPersonByErpId...");
        java.lang.String _getPersonByErpId_arg0 = "";
        eu.ebbitsproject.peoplemanager.Person _getPersonByErpId__return = port.getPersonByErpId(_getPersonByErpId_arg0);
        System.out.println("getPersonByErpId.result=" + _getPersonByErpId__return);


        }
        {
        System.out.println("Invoking isPersonAvailableByErpId...");
        java.lang.String _isPersonAvailableByErpId_arg0 = "";
        boolean _isPersonAvailableByErpId__return = port.isPersonAvailableByErpId(_isPersonAvailableByErpId_arg0);
        System.out.println("isPersonAvailableByErpId.result=" + _isPersonAvailableByErpId__return);


        }
        {
        System.out.println("Invoking getPersons...");
        java.util.List<eu.ebbitsproject.peoplemanager.Person> _getPersons__return = port.getPersons();
        System.out.println("getPersons.result=" + _getPersons__return);


        }
        {
        System.out.println("Invoking getPersonById...");
        java.lang.String _getPersonById_arg0 = "";
        eu.ebbitsproject.peoplemanager.Person _getPersonById__return = port.getPersonById(_getPersonById_arg0);
        System.out.println("getPersonById.result=" + _getPersonById__return);


        }

        System.exit(0);
    }

}
