package eu.ebbitsproject.peoplemanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-15T23:24:51.370+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://peoplemanager.ebbitsproject.eu/", name = "RuleEnginePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface RuleEnginePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEvents", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetEvents")
    @WebMethod
    @ResponseWrapper(localName = "getEventsResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetEventsResponse")
    public java.util.List<eu.ebbitsproject.peoplemanager.Event> getEvents();

    @RequestWrapper(localName = "insertEvent", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.InsertEvent")
    @WebMethod
    @ResponseWrapper(localName = "insertEventResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.InsertEventResponse")
    public void insertEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isPersonAvailableById", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableById")
    @WebMethod
    @ResponseWrapper(localName = "isPersonAvailableByIdResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableByIdResponse")
    public boolean isPersonAvailableById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isPersonAvailableByRfid", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableByRfid")
    @WebMethod
    @ResponseWrapper(localName = "isPersonAvailableByRfidResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableByRfidResponse")
    public boolean isPersonAvailableByRfid(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "updateEvent", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.UpdateEvent")
    @WebMethod
    @ResponseWrapper(localName = "updateEventResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.UpdateEventResponse")
    public void updateEvent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByErpId", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersonByErpId")
    @WebMethod
    @ResponseWrapper(localName = "getPersonByErpIdResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersonByErpIdResponse")
    public eu.ebbitsproject.peoplemanager.Person getPersonByErpId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isPersonAvailableByErpId", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableByErpId")
    @WebMethod
    @ResponseWrapper(localName = "isPersonAvailableByErpIdResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.IsPersonAvailableByErpIdResponse")
    public boolean isPersonAvailableByErpId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersons")
    @WebMethod
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersonsResponse")
    public java.util.List<eu.ebbitsproject.peoplemanager.Person> getPersons();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersonById")
    @WebMethod
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://peoplemanager.ebbitsproject.eu/", className = "eu.ebbitsproject.peoplemanager.GetPersonByIdResponse")
    public eu.ebbitsproject.peoplemanager.Person getPersonById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
